---
title: "Shiny_App"
output: html_document
date: "2025-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)
library(shinydashboard)
library(naniar)
library(janitor)
library(readr)
```

```{r}
# tvs <- read_csv("Desktop/BIS15W2025_group10-main/data/tv_only.csv") # Lab Macs
tvs <- read_csv("data/tv_only.csv") # Personal Laptop
tvs <- rename(tvs, name = "movies")
```


```{r}
library(shiny)

ui <- fluidPage(
  dashboardPage(
    dashboardHeader(title = "Test"),
    dashboardSidebar(
      sidebarMenu(
        menuItem("Ratings vs. Year", 
                 tabName = "ratings", 
                 icon = icon("dashboard")),
        menuItem("Comparisons", 
                 tabName = "comps", 
                 icon = icon("th")),
        menuItem("Show Recommendations", 
                 tabName = "recs", 
                 icon = icon("th")),
        menuItem("Top Shows by Genre",
                 tabName = "top_by_genre",
                 icon = icon("th")),
        menuItem("Distribution of Ratings by Genre",
                 tabName = "dist_by_genre",
                 icon = icon("th"))
      )
    ),
    dashboardBody(
      tags$head(
        tags$style(HTML(".box{border-radius: 10px; box-shadow: 3px 3px 5px #888888;}"))
      ),
      
      tabItems(
        tabItem(
          tabName = "ratings",
          fluidRow(
            box(
              title = "Variables",
              width = 3, #adjust the column width
              selectInput("tab1_var", "Select Variable", choices = c("start_year", "votes"), selected = "start_year")
            ), # close the first box    
      
            box(title = "Ratings vs.", width = 8, #adjust the column width and add title
              plotOutput("plot_ratings", width = "500px", height = "400px")
            ) # close the second box
          ) # close the row
        ),
        tabItem(
          tabName = "comps",
          fluidRow(
            box(
              title = "Top X in Ratings",
              plotOutput("plot_comps")
            ) # close box
          )
        ), # close tabItem
      tabItem(
        tabName = "top_by_genre",
        fluidRow(
     box(
       width = 4,
       selectInput(
         "genre",
         "Select Genre",
         choices = c("Action (391 shows)", "Adventure (290	shows)", "Animation (390 shows)", "Biography (58 shows)", "Comedy (549 shows)", "Crime (326 shows)", "Documentary (273 shows)", "Drama (854 shows)", "Family (130 shows)", "Fantasy (126 shows)", "Film-Noir (3 shows)", "Game-Show (27 shows)", "History (68 shows)", "Horror (117 shows)", "Music (48 shows)", "Musical (11 shows)", "Mystery (172 shows)", "News (1 show)", "Reality-TV (165 shows)", "Romance (168 shows)", "Sci-Fi (85 shows)", "Short (44 shows)", "Sport (37 shows)", "Talk-Show (16 shows)", "Thriller (147 shows)", "War (10 shows)", "Western (9 shows)"),
         selected = "Action (1,447 shows)"
       ), # close SelectInput
       textInput("top",
                 "Highest Ranking",
                 value = "1"
                 ), # close textInput
       textInput("bottom",
                 "Lowest Ranking",
                 value = "10"
                 ) #close textInput
     ), # close box
     box(
       width = 8,  # Adjust width
        plotOutput("plot1", width = "500px", height = "300px")
     ), # close box
     box(
       width = 8,
       tableOutput("table")
     ) # close box
   ) # close fluidRow
      ), # close tabItem
   tabItem(
     tabName = "dist_by_genre",
     fluidRow(
      box(
        width = 4,  # Adjust width
        selectInput(
          "x0",
          "Select Plot Type",
          choices = c("Density Plot", "Box Plot"),
          selected = "Density Plot"
        ),
        selectInput(
          "x1",
          "Select Genre 1",
          choices = c("Action", "Adventure", "Animation", 
                      "Biography", "Comedy", "Crime", "Documentary", 
                      "Drama", "Family", "Fantasy", 
                      "Game-Show", "History", "Horror", "Music", 
                      "Musical", "Mystery", "Reality-TV", 
                      "Romance", "Sci-Fi", "Short", "Sport", "Talk-Show", 
                      "Thriller", "War"),
          selected = "Action"
        ),
        selectInput(
          "x2",
          "Select Genre 2",
          choices = c("Action", "Adventure", "Animation", 
                      "Biography", "Comedy", "Crime", "Documentary", 
                      "Drama", "Family", "Fantasy", 
                      "Game-Show", "History", "Horror", "Music", 
                      "Musical", "Mystery", "Reality-TV", 
                      "Romance", "Sci-Fi", "Short", "Sport", "Talk-Show", 
                      "Thriller", "War"),
          selected = "Adventure"
        )
      ),
      box(
        width = 8,  # Adjust width
        plotOutput("plot1d", width = "500px", height = "300px"),
        plotOutput("plot2d", width = "500px", height = "300px")
      )
    )
   ) # close tabItem
      ) # close tabItems
    )
  )
)

server <- function(input, output, session) {
  session$onSessionEnded(stopApp) # stop the app when we close it
  output$plot_ratings <- renderPlot({
    tvs %>% 
      select(rating, !!sym(input$tab1_var)) %>% 
      group_by(!!sym(input$tab1_var)) %>% 
      summarize(mean = mean(rating, na.rm = T)) %>% 
      arrange(!!sym(input$tab1_var)) %>% 
      ggplot(aes_string(x = input$tab1_var, y = "mean", fill = "mean", color = "mean"))+
      geom_line()+
      geom_point() +
      scale_x_log10()
  })
  
  output$plot_comps <- renderPlot({
    dir1 <- tvs %>% 
      select(name, director_1, rating) %>% 
      filter(director_1 != "NA") %>% 
      rename(director = director_1)
    
    dir2 <- tvs %>% 
      select(name, director_2, rating) %>% 
      filter(director_2 != "NA") %>% 
      mutate(director_2 = trimws(director_2)) %>% 
      rename(director = director_2)
    
    director_full <- bind_rows(dir1, dir2) %>% 
      filter(rating != "NA") %>% 
      select(director, rating)
    
    fake <- c(1:2714)
    
    director_full <- tibble(fake, director_full)
    
    director_full <- director_full %>% # errors out at row 2939 because there are multiple entries with the same movie and director that have different ratings
      pivot_wider(
                  names_from = director,
                  values_from = rating) %>% 
      summarise(across(everything(), mean, na.rm = T)) %>% 
      select(-fake) %>% 
      pivot_longer(cols = everything(), names_to = "director",
                   values_to = "mean_rating") %>% 
      arrange(-mean_rating) 
      
    director_full[1:10, ] %>% 
      ggplot(aes(x = reorder(director, mean_rating), y = mean_rating, fill = director)) +
      geom_col() +
      labs(title = "Average Rating of Directors",
           x = "Director",
           y = "Average Rating of Movies") +
      coord_flip()
  }) # close renderPlot
  
  output$table <- renderTable(
    tv %>% 
  filter(rating != "NA") %>% 
  rename(name = "movies") %>% 
  select(name, genre_1, genre_2, genre_3, rating) %>% 
  group_by(name, genre_1, genre_2, genre_3) %>% 
  summarize(rating = mean(rating, na.rm = TRUE), .groups = 'drop') %>%
  filter(genre_1 == str_extract(input$genre, "\\S+") | genre_2 == str_extract(input$genre, "\\S+") | genre_3 == str_extract(input$genre, "\\S+")) %>% 
  mutate(rating = signif(rating, digits = 2)) %>% 
  arrange(-rating) %>%     
    slice(as.numeric(input$top):as.numeric(input$bottom)) %>% 
    select(name, rating) %>% 
    mutate(ranking = c(as.numeric(input$top):as.numeric(input$bottom))) %>% 
    relocate(ranking, .before = name)
  ) # close renderTable
  
  output$plot1 <- renderPlot({
    tv %>% 
  filter(rating != "NA") %>% 
  rename(name = "movies") %>% 
  select(name, genre_1, genre_2, genre_3, rating) %>% 
  group_by(name, genre_1, genre_2, genre_3) %>% 
  summarize(rating = mean(rating, na.rm = TRUE), .groups = 'drop') %>%
  filter(genre_1 == str_extract(input$genre, "\\S+") | genre_2 == str_extract(input$genre, "\\S+") | genre_3 == str_extract(input$genre, "\\S+")) %>% 
  mutate(rating = signif(rating, digits = 2)) %>% 
  arrange(-rating) %>%     
  slice(as.numeric(input$top):as.numeric(input$bottom)) %>% 
  ggplot(aes(x = reorder(name, rating), y = rating))+
  geom_col(fill = "steelblue")+
  scale_y_continuous(limits = c(0, 10))+
  coord_flip()+
  labs(x = "Rating",
       y = "Show Name")
  }) # close renderPlot

  output$plot1d <- renderPlot({
    genre <- tv %>% filter(genre_1 == input$x1 | genre_2 == input$x1 | genre_3 == input$x1)
    
    if (input$x0 == "Density Plot") {
      ggplot(genre, aes(x = rating)) +
        geom_density(color = "red") +
        geom_histogram(aes(y = after_stat(density)), fill = "steelblue", alpha = 0.4, color = "black", alpha = 0.1)+
        scale_x_continuous(limits = c(0, 10)) +
        scale_y_continuous(limits = c(0, 1)) +
        labs(title = input$x1)
    } else {
      ggplot(genre, aes(x = rating)) +
        geom_boxplot() +
        scale_x_continuous(limits = c(0, 10)) +
        labs(title = input$x1) +
        theme(axis.ticks.y = element_blank(),
              axis.text.y = element_blank())
    }
  })
  
  output$plot2d <- renderPlot({
    filtered_data <- tv %>% filter(genre_1 == input$x2 | genre_2 == input$x2 | genre_3 == input$x2)
    
    if (input$x0 == "Density Plot") {
      ggplot(filtered_data, aes(x = rating)) +
        geom_density(color = "red") +
        geom_histogram(aes(y = after_stat(density)), fill = "steelblue", alpha = 0.4, color = "black", alpha = 0.1)+
        scale_x_continuous(limits = c(0, 10)) +
        scale_y_continuous(limits = c(0, 1)) +
        labs(title = input$x2)
    } else {
      ggplot(filtered_data, aes(x = rating)) +
        geom_boxplot() +
        scale_x_continuous(limits = c(0, 10)) +
        labs(title = input$x2) +
        theme(axis.ticks.y = element_blank(),
              axis.text.y = element_blank())
    }
  }) # renderPlot
  } # last bracket

shinyApp(ui, server)
```

