---
title: "tab4_density_box"
author: "Daniel Yang"
date: "2025-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load data
```{r}
library(tidyverse)
tv <- read_csv("/Users/danielyang/Downloads/BIS15W2025_group10-main/data/tv_only.csv")
```

# Shiny App Density and Box Plot
```{r}
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)

# Sample dataset (Replace 'tv' with your actual dataset)
# tv <- read.csv("your_data.csv")

ui <- dashboardPage(
  dashboardHeader(title = "Distribution of Show Ratings by Genre"),
  dashboardSidebar(disable = TRUE),
  dashboardBody(
    fluidRow(
      box(
        width = 4,  # Adjust width
        selectInput(
          "x0",
          "Select Plot Type",
          choices = c("Density Plot", "Box Plot"),
          selected = "Density Plot"
        ),
        selectInput(
          "x1",
          "Select Genre 1",
          choices = c("Action", "Adventure", "Animation", 
                      "Biography", "Comedy", "Crime", "Documentary", 
                      "Drama", "Family", "Fantasy", 
                      "Game-Show", "History", "Horror", "Music", 
                      "Musical", "Mystery", "Reality-TV", 
                      "Romance", "Sci-Fi", "Short", "Sport", "Talk-Show", 
                      "Thriller", "War"),
          selected = "Action"
        ),
        selectInput(
          "x2",
          "Select Genre 2",
          choices = c("Action", "Adventure", "Animation", 
                      "Biography", "Comedy", "Crime", "Documentary", 
                      "Drama", "Family", "Fantasy", 
                      "Game-Show", "History", "Horror", "Music", 
                      "Musical", "Mystery", "Reality-TV", 
                      "Romance", "Sci-Fi", "Short", "Sport", "Talk-Show", 
                      "Thriller", "War"),
          selected = "Adventure"
        )
      ),
      box(
        width = 8,  # Adjust width
        plotOutput("plot1", width = "500px", height = "300px"),
        plotOutput("plot2", width = "500px", height = "300px")
      )
    )
  )
)

server <- function(input, output, session) {
  
  output$plot1 <- renderPlot({
    genre <- tv %>% filter(genre_1 == input$x1 | genre_2 == input$x1 | genre_3 == input$x1)
    
    if (input$x0 == "Density Plot") {
      ggplot(genre, aes(x = rating)) +
        geom_density(color = "red") +
        geom_histogram(aes(y = after_stat(density)), fill = "steelblue", alpha = 0.4, color = "black", alpha = 0.1)+
        scale_x_continuous(limits = c(0, 10)) +
        scale_y_continuous(limits = c(0, 1)) +
        labs(title = input$x1)
    } else {
      ggplot(genre, aes(x = rating)) +
        geom_boxplot() +
        scale_x_continuous(limits = c(0, 10)) +
        labs(title = input$x1) +
        theme(axis.ticks.y = element_blank(),
              axis.text.y = element_blank())
    }
  })
  
  output$plot2 <- renderPlot({
    filtered_data <- tv %>% filter(genre_1 == input$x2 | genre_2 == input$x2 | genre_3 == input$x2)
    
    if (input$x0 == "Density Plot") {
      ggplot(filtered_data, aes(x = rating)) +
        geom_density(color = "red") +
        geom_histogram(aes(y = after_stat(density)), fill = "steelblue", alpha = 0.4, color = "black", alpha = 0.1)+
        scale_x_continuous(limits = c(0, 10)) +
        scale_y_continuous(limits = c(0, 1)) +
        labs(title = input$x2)
    } else {
      ggplot(filtered_data, aes(x = rating)) +
        geom_boxplot() +
        scale_x_continuous(limits = c(0, 10)) +
        labs(title = input$x2) +
        theme(axis.ticks.y = element_blank(),
              axis.text.y = element_blank())
    }
  })
  
}

shinyApp(ui, server)

```

